### ISSUE TITLE
How to Run Tests?  Error: Cannot find module 'tape'

### ISSUE THREAD

**Issue by iarobinson** [indiesquidge/javascript-challenges#3]
**While following this instruction I ran into a wall:**

Run `node most-recurrent-test.js` to run the test suite in full.

**An error was thrown in terminal that read as follows**

$ node most-recurrent-test.js
module.js:442
    throw err;
    ^

Error: Cannot find module 'tape'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Ian/Desktop/codeTests/javascript-challenges/number-frequency/most-recurrent-test.js:1:76)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

_I became lost while trying to debug this. Thoughts?_

**Comment by FarisMarouane** [comment]
You should do "npm install" first to install all the modules required by the project.

**Comment by indiesquidge** [comment]
Hi, @iarobinson! Marouane is correct, you have to install the dependencies with the command `npm install` while in the project root (the level with the `package.json` file).

I have updated the readme to include this step in the setup process :)
